const worksData = [
  // ===== 逢沢みゆ =====
  {
    id: 1,
    title: '『逢沢みゆ』が媚薬の背徳感に溺れ、美巨乳デカ尻震わせ生中出しにヨガり狂うド淫乱3SEX',
    actress: '逢沢みゆ',
    maker: 'セレブの友',
    code: 'CEAD-750',
    date: '2026-06-06',
    tags: ['単体作品', '巨乳', '痴女', '中出し'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/cead00750/cead00750pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=cead00750&i3_ref=list&i3_ord=1&i3_pst=1&dmmref=video_list'
  },
  {
    id: 18,
    title: '中出しが出来ない隣人既婚者に\'唾液マーキング不倫\'で全身おぼれさせ 逢沢みゆ',
    actress: '逢沢みゆ',
    maker: 'YONAKA',
    code: 'MOON-057',
    date: '2026-05-31',
    tags: ['単体作品', '巨乳'],
    badge: null,
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/1moon00057/1moon00057pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=1moon00057&i3_ref=list&i3_ord=6&i3_pst=1&dmmref=video_list'
  },
  {
    id: 19,
    title: 'おじさんの好きにシテいいよ。逢沢みゆ',
    actress: '逢沢みゆ',
    maker: 'S-Cute',
    code: 'SQTE-689',
    date: '2026-05-30',
    tags: ['単体作品', '美少女', 'ハメ撮り', '中出し'],
    badge: null,
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/sqte00689/sqte00689pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=sqte00689&i3_ref=list&i3_ord=7&i3_pst=1&dmmref=video_list'
  },

  // ===== 佐野秋帆 =====
  {
    id: 20,
    title: '【VR】【8K】新婚妊活中だけど妻の妹にベロベロ舐められ何度も搾り取られて妻と夜の営みが出来ません汗 佐野秋帆',
    actress: '佐野秋帆',
    maker: 'unfinished',
    code: 'URVRSP-576',
    date: '2026-06-05',
    tags: ['単体作品', 'VR', '巨乳', '痴女', '中出し'],
    badge: 'VR',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/urvrsp00576/urvrsp00576pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=urvrsp00576&i3_ref=search&i3_ord=1&i3_pst=1&dmmref=video_search'
  },
  {
    id: 21,
    title: '息子の嫁は変態痴女。欲求不満のGカップドS妻が、同居する義父を徹底的に性奴●にする完全飼育 佐野秋帆',
    actress: '佐野秋帆',
    maker: '七狗留',
    code: 'NACT-135',
    date: '2026-06-05',
    tags: ['単体作品', '痴女'],
    badge: '4K',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/h_237nact00135/h_237nact00135pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=h_237nact00135&i3_ref=search&i3_ord=2&i3_pst=1&dmmref=video_search'
  },
  {
    id: 22,
    title: '【VR】【8K】友人の姉ちゃんは童貞キラー！校内で噂のエロいお姉さんが童貞チ○ポを谷間と色気で誘惑して筆おろし中出しSEXしてあげる 佐野秋帆',
    actress: '佐野秋帆',
    maker: 'unfinished',
    code: 'URVRSP-569',
    date: '2026-05-22',
    tags: ['単体作品', 'VR', '巨乳', '痴女', '中出し'],
    badge: 'VR',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/urvrsp00569/urvrsp00569pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=urvrsp00569&i3_ref=search&i3_ord=5&i3_pst=1&dmmref=video_search'
  },
  {
    id: 23,
    title: '度が過ぎた玩具責めに失神寸前！子宮陥落オホイキSEX@さみたん（仮） 佐野秋帆',
    actress: '佐野秋帆',
    maker: '素人CLOVER',
    code: 'STCV-596',
    date: '2026-05-08',
    tags: ['単体作品', 'ハメ撮り'],
    badge: null,
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/1stcv00596/1stcv00596pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=1stcv00596&i3_ref=search&i3_ord=6&i3_pst=1&dmmref=video_search'
  },
  {
    id: 24,
    title: '夫に求められないレス妻は、夫が寝ている横で彼の同僚に堕ちていく 佐野秋帆',
    actress: '佐野秋帆',
    maker: '七狗留',
    code: 'NACT-112',
    date: '2026-04-05',
    tags: ['単体作品', '人妻', '中出し'],
    badge: null,
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/h_237nact00112/h_237nact00112pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=h_237nact00112&i3_ref=search&i3_ord=10&i3_pst=1&dmmref=video_search'
  },
  {
    id: 25,
    title: '【この女、仕事の為なら何でもする。】営業部エースの人妻生保レディ 浴衣で乱れイキ狂う湯けむり不貞性接待 佐野秋帆',
    actress: '佐野秋帆',
    maker: '街角シロウトナンパ',
    code: 'MAAN-1155',
    date: '2026-03-15',
    tags: ['単体作品', '人妻', '巨乳', 'ハメ撮り', '中出し'],
    badge: null,
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/h_1711maan01155/h_1711maan01155pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=h_1711maan01155&i3_ref=search&i3_ord=11&i3_pst=1&dmmref=video_search'
  },
  {
    id: 26,
    title: 'お客様には決して見せない、着物で隠れた純白Gカップと淫らな人妻セックス 料亭の美人女将 佐野秋帆（28）AVデビュー',
    actress: '佐野秋帆',
    maker: 'E-BODY',
    code: 'EYAN-208',
    date: '2026-01-20',
    tags: ['単体作品', '人妻'],
    badge: null,
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/eyan00208/eyan00208pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=eyan00208&i3_ref=search&i3_ord=12&i3_pst=1&dmmref=video_search'
  },

  // ===== その他新着作品 =====
  {
    id: 2,
    title: '中出しの快楽に堕ちた妻 三池小春',
    actress: '三池小春',
    maker: 'タカラ映像',
    code: 'ALDN-590',
    date: '2026-06-06',
    tags: ['単体作品', '人妻', '熟女', '中出し'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/aldn00590/aldn00590pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=aldn00590&i3_ref=list&i3_ord=23&i3_pst=1&dmmref=video_list'
  },
  {
    id: 3,
    title: '「黒咲華」を本気で酔わせたら～性欲暴走リアルSEXドキュメント',
    actress: '黒咲華',
    maker: 'セレブの友',
    code: 'CEMD-853',
    date: '2026-06-06',
    tags: ['単体作品', '巨乳', '乱交', '中出し'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/cemd00853/cemd00853pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=cemd00853&i3_ref=list&i3_ord=4&i3_pst=1&dmmref=video_list'
  },
  {
    id: 4,
    title: 'ノーブラ熟巨乳ムチムチおっぱいデート～酒飲み●っぱらい編 波多野結衣',
    actress: '波多野結衣',
    maker: 'セレブの友',
    code: 'CEMD-851',
    date: '2026-06-06',
    tags: ['単体作品', '巨乳', '中出し', '野外・露出'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/cemd00851/cemd00851pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=cemd00851&i3_ref=list&i3_ord=13&i3_pst=1&dmmref=video_list'
  },
  {
    id: 5,
    title: 'お義母さん、にょっ女房よりずっといいよ… 葉山さゆり',
    actress: '葉山さゆり',
    maker: 'タカラ映像',
    code: 'ALDN-588',
    date: '2026-06-06',
    tags: ['単体作品', '人妻', '熟女', '巨乳', '中出し'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/aldn00588/aldn00588pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=aldn00588&i3_ref=list&i3_ord=21&i3_pst=1&dmmref=video_list'
  },
  {
    id: 6,
    title: 'ニップルチェーン嵌められ乳首ぷらぷら一日中チク勃起の人妻は不倫男の激ピスに見たことないチク軌道で爆揺れ爆イキ中出し懇願する乳マゾ女になり果てた 九井スナオ',
    actress: '九井スナオ',
    maker: 'アリスJAPAN',
    code: 'DVAJ-743',
    date: '2026-06-06',
    tags: ['単体作品', '人妻', '巨乳', '中出し'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/dvaj00743/dvaj00743pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=dvaj00743&i3_ref=list&i3_ord=25&i3_pst=1&dmmref=video_list'
  },
  {
    id: 7,
    title: '初心童貞をレンタルしたら内なるドS性が開花しキンタマ空にあんるまで搾り取る系女子2人 りんちゃんとみそのちゃん',
    actress: 'りんちゃん・みそのちゃん',
    maker: '俺の素人-Z- SECOND IMPACT',
    code: 'ORECS-593',
    date: '2026-06-06',
    tags: ['痴女', '巨乳', '中出し', '素人'],
    badge: 'NEW',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/h_1732orecs00593/h_1732orecs00593jp-1.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=h_1732orecs00593&i3_ref=list&i3_ord=69&i3_pst=1&dmmref=video_list'
  },
  {
    id: 8,
    title: '【4K】隣の奥様は美巨乳インストラクター 爆乳肉感ボディで大胆誘惑 夢にまで見た神展開で禁断中出し不倫SEX 小梅えな',
    actress: '小梅えな',
    maker: 'クリスタル映像',
    code: 'MADM-219',
    date: '2026-06-06',
    tags: ['単体作品', '人妻', '巨乳', '中出し'],
    badge: '4K',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/madm00219/madm00219pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=madm00219&i3_ref=list&i3_ord=103&i3_pst=1&dmmref=video_list'
  },
  {
    id: 9,
    title: '【初撮り】ネットでAV応募→AV体験撮影 2569 ひめか 27歳 小学校の音楽の先生',
    actress: 'ひめか（27歳）',
    maker: 'シロウトTV',
    code: 'SIRO-5680',
    date: '2026-06-07',
    tags: ['ハメ撮り', '巨乳', '素人'],
    badge: 'NEW',
    thumb: 'https://image.mgstage.com/images/shirouto/siro/5680/pb_p_siro-5680.jpg',
    url: 'https://www.mgstage.com/product/product_detail/SIRO-5680/'
  },
  {
    id: 10,
    title: 'おっぱいだけ大きければ全部解決する！この世の真理に気付いてしまった逆ナン女子のエロ過ぎる無双ムーブ。',
    actress: 'ゆうかちゃん（21歳）',
    maker: 'いきなりせんべろ逆ナンパ',
    code: '300MIUM-1345',
    date: '2026-06-07',
    tags: ['素人', '巨乳'],
    badge: 'NEW',
    thumb: 'https://image.mgstage.com/images/prestigepremium/300mium/1345/pb_e_300mium-1345.jpg',
    url: 'https://www.mgstage.com/product/product_detail/300MIUM-1345/'
  },
  {
    id: 11,
    title: 'わざわざDMしてきたアイドルとの密会。挿れた瞬間からとろけた顔してイキ狂ってる。可愛い過ぎるキラキラのお顔に遠慮なくぶっかけてあげました、、、',
    actress: 'める（22歳）',
    maker: 'くりーむぱい',
    code: '857OMG-031',
    date: '2026-06-07',
    tags: ['ハメ撮り', '美少女', '素人'],
    badge: 'NEW',
    thumb: 'https://image.mgstage.com/images/creampie/857omg/031/pb_e_857omg-031.jpg',
    url: 'https://www.mgstage.com/product/product_detail/857OMG-031/'
  },
  {
    id: 12,
    title: '【初撮り】ネットでAV応募→AV体験撮影 2568 ひな 27歳 インフォメーション受付',
    actress: 'ひな（27歳）',
    maker: 'シロウトTV',
    code: 'SIRO-5679',
    date: '2026-06-07',
    tags: ['ハメ撮り', '素人'],
    badge: 'NEW',
    thumb: 'https://image.mgstage.com/images/shirouto/siro/5679/pb_e_siro-5679.jpg',
    url: 'https://www.mgstage.com/product/product_detail/SIRO-5679/'
  },
  {
    id: 13,
    title: '家まで送ってイイですか？case.295 田野さん/23歳/キャバ嬢',
    actress: '田野さん（23歳）',
    maker: 'ドキュメンTV',
    code: '277DCV-302',
    date: '2026-06-05',
    tags: ['ハメ撮り', '素人', '企画'],
    badge: null,
    thumb: 'https://image.mgstage.com/images/documentv/277dcv/302/pb_e_277dcv-302.jpg',
    url: 'https://www.mgstage.com/product/product_detail/277DCV-302/'
  },
  {
    id: 14,
    title: '【VR】超絶おっぱい空間 ハーレムパコパコなまSEX 桜ゆの 胡桃さくら 宮西ひかる',
    actress: '桜ゆの・胡桃さくら・宮西ひかる',
    maker: 'KMPVR-彩-',
    code: 'SAVR-1077',
    date: '2026-06-07',
    tags: ['VR', '巨乳', '痴女', '中出し'],
    badge: 'VR',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/savr01077/savr01077pl.jpg?w=560&h=360&f=webp&t=margin',
    url: 'https://video.dmm.co.jp/av/content/?id=savr01077&i3_ref=list&i3_ord=15&i3_pst=1&dmmref=video_list'
  },
  {
    id: 15,
    title: '【アナルも舐める積極美女】しなやかなカラダがたまらん美容部員！コスプレ姿をバックから鬼ピス大量中出し！！【可憐な隣人】【みゆ】',
    actress: '石野未夢',
    maker: '街角シロウトナンパ',
    code: 'MAAN-1174',
    date: '2026-06-07',
    tags: ['素人', '中出し'],
    badge: 'NEW',
    thumb: 'https://image.mgstage.com/images/doc/maan/1174/pb_e_maan-1174.jpg',
    url: 'https://www.mgstage.com/product/product_detail/MAAN-1174/'
  },
  {
    id: 16,
    title: 'ガチ歯科衛生士さんプライベートお口セックス あかりさん(24)とももさん(23)',
    actress: 'あかりさん・ももさん',
    maker: '俺の素人-Z-SECONDIMPACT',
    code: 'ORECS-594',
    date: '2026-06-07',
    tags: ['素人', '中出し'],
    badge: 'NEW',
    thumb: 'https://image.mgstage.com/images/orenoshiroutozsecond/765orecs/594/pb_e_765orecs-594.jpg',
    url: 'https://www.mgstage.com/product/product_detail/765ORECS-594/'
  },
  {
    id: 17,
    title: '金松季歩を秒で全裸！秒でSEX！「えっ！ここは本当にムりぃぃぃ！！！」ドッキリ即ズボGP！',
    actress: '金松季歩',
    maker: 'エスワン ナンバーワンスタイル',
    code: 'SNOS-232',
    date: '2026-06-05',
    tags: ['単体作品', '巨乳', 'ハメ撮り'],
    badge: '4K',
    thumb: 'https://awsimgsrc.dmm.co.jp/pics_dig/digital/video/snos00232/snos00232pl.jpg?f=webp',
    url: 'https://video.dmm.co.jp/av/content/?id=snos00232&i3_ref=recommend&i3_ord=4&i3_pst=1&dmmref=pickup_video_list'
  },
];
